### PR TITLE
Adding Forms to the website

### PR DESCRIPTION
**Pull request by haikelfd**

### CODE REVIEW

**Comment by haikelfd** [comment]
Work in progress

**Comment by francisli** [comment]
@haikelfd @JesusEArambula just FYI, I pushed a commit to the branch, so make sure to do a `git pull` next time before you start working... I made some changes to the Form model so that it properly handles photo file attachments...

**Comment by francisli** [comment]
@haikelfd @JesusEArambula @GaelGil is someone going to finish the work on this branch for forms...?

Note that there is also a "conflict" being reported due to new changes on master branch. @GaelGil can you walk the team through how to resolve a merge conflict? I'm out of town this week, but will try to finish reviewing all the branches remotely...

**Comment by francisli** [comment]
Since https://github.com/dev-mission/sfdreamer/pull/32 has completed the Forms implementation first, I'd suggest closing/abandoning this branch in favor of the other one.

**Pull request closed without merging**
